### ISSUE TITLE
Implement a selection form for 'Ordinary Member' and 'Cooperator

### ISSUE THREAD

**Issue by michaellaunay** [michaellaunay/alirpunkto#10]
---

**Objective**: 
Provide users with a clear interface allowing them to choose between registering as a "Ordinary Member" or a "Cooperator".

---

**Description**:

1. **Header**:
   - Display a title: "Membership Type".
   - A subtitle briefly explaining the differences between a "Ordinary Member" and a "Cooperator".

2. **Content**:
   - Two buttons or checkboxes:
     - "Ordinary Member": with a brief description or a link for more details.
     - "Cooperator": with a brief description or a link for more details.

3. **Actions**:
   - When a choice is selected, the form should highlight this choice (e.g., using a different style or ticking a box).
   - A "Continue" button to proceed to the next registration step.

4. **Footer**:
   - A "Back" link to return to the previous registration step.
   - Links to the privacy policy, terms of use, and contact details.

---

**Mockups**: 
Mockups should show what the form will look like on different devices (desktop, tablet, mobile).
[Mockups](https://github.com/michaellaunay/alirpunkto/tree/master/docs/mockups)

---

**Acceptance Criteria**:

1. The form loads correctly and without errors.
2. Users can easily differentiate and select the membership type.
3. The "Continue" button functions correctly and leads to the next registration step.
4. Design is responsive and displays correctly on all devices and screen sizes.

---

**Dependencies**:
- A design mockup needs to be ready.
- Business logic for handling the selected member type should be set up in the backend.

---

**Notes**:
- Ensure that brand guidelines and styling are adhered to when creating the form.
- Descriptions for "Ordinary Member" and "Cooperator" should be clear and concise to assist the user in making an informed choice.

---

**Priority**: High, as it impacts the type of membership and associated rights on the platform.

**Time Estimate**: 2 days (1 day for setting up the basic structure, 1/2 day for styling and design, 1/2 day for testing and revisions).

**Comment by SergioArbarviro** [comment]
The name "Regular member" should be changed to "Ordinary member".
