### ISSUE TITLE
There should be no information bubble attached to the links to the external applications

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#143]
### Current state
On the page with the list of applications to which the connection to AlirPunkto gives access to, when hovering over the links related to these applications, an information bubble appears with a technical text 
```
Project-Id-Version: 0.1 
Report-Msgid-Bugs-To: .... etc.
```
### Desired state
These information bubbles should not be present.

**Comment by michaellaunay** [comment]
see #128
