### ISSUE TITLE
The verification of matching between the "password" and "password_confirm" variables in the "Reset password" process does not work

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#152]
### Current state

A user (Fabrice) has reported trying to reset his password. He believes that he wrote twice the same characters string in the `password` and `password_confirm` fields. However, he receives the message that they don't match.

In the absence of a feature enabling to visualise the text in theses fields, he cannot control whether he made a mistake, of if it is the machine.

### Desired state
The error message `password_not_match` should be displayed only when indeed the two variables  `password` and `password_confirm` do not match.

It would be nice if the user could have the option to visualise in clear text the values that s/he provides to both variables, in order to control by him/herself whether the input is correct.

**Comment by michaellaunay** [comment]
I propose to allow the option to show or hide passwords in the input field.

**Comment by SergioArbarviro** [comment]
@michaellaunay I agree with your proposal.

**Comment by SergioArbarviro** [comment]
The nature and possible origin of the bug have been identified and are now in issue #153 
The addition of a possibility to visualise the password when setting it is now the purpose of issue #154
