### ISSUE TITLE
The "forgot password" process loops with the error code "password_required"

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#153]
### Current state
In the "[forgot password" process](https://github.com/michaellaunay/alirpunkto/blob/master/alirpunkto/views/forgot_password.py), after the user has provided a valid password with password and confirmation matching, AlirPunkto  displays the error message with code `password_required`. Whatever the number of times the user provides the password, the error persists.

### Desired state
In this process, following the provision of a valid password with password and confirmation matching, AlirPunkto should continue the process with no error and confirm the password change.

### Hypothesis on the source of the error

On line https://github.com/michaellaunay/alirpunkto/blob/f0445ad5a64598200e9aca24a2f23ebc46b2e5be/alirpunkto/views/forgot_password.py#L207
the variable `err` is associated with a **valid** password and generates the error code `password_required` in line
https://github.com/michaellaunay/alirpunkto/blob/f0445ad5a64598200e9aca24a2f23ebc46b2e5be/alirpunkto/views/forgot_password.py#L210
, whereas it should be the opposite: the variable `err` should be associated with an **invalid** password.

**Comment by michaellaunay** [comment]
The is_not_a_valid_email_address function returns a dictionary with an error code if it fails, None otherwise. The problem is that the flash message is not displayed.
The flash message would then indicate that the passwords do not meet the security criteria. The issue to be addressed is therefore to replace the flash message with the display of the error.

**Comment by SergioArbarviro** [comment]
Solved by commit 016828045e257ce91ae07bff9cf55526e8692cb5
