### ISSUE TITLE
Process: the start page should explain what the registration options are

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#16]
On the start page, the system proposes two options for registration:

- ordinary Member of the Community;
- Cooperator.

However, no explanation is given at this point regarding what these options mean or imply.

I believe that an explanatory text should be provided there, before any choice is made by the user.

**Comment by michaellaunay** [comment]
Debugging in progress, there is an issue with storing the password in LDAP, I need to configure the OpenLDAP server to use bcrypt so that the code {BCRYPT}Password works.

**Comment by michaellaunay** [comment]
Debugging in progress, there is an issue with storing the password in LDAP, I need to configure the OpenLDAP server to use bcrypt so that the code {BCRYPT}Password works.
