### ISSUE TITLE
The name of the dynamic group containing all members of the Community should be "communityMembersGroup"

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#161]
### Current state
Two names exist in the LDAP directory that refer to the same members, in the same state. None of them is consistent, and they are source of confusion:

- `communityGroup`
- `ordinaryMembersGroup`

### Desired state
For the sake of consistency between names and the underlying reality, and because of duplicates in the names given to dynamic groups, there should be only one dynamic group, with the name: 

**`communityMembersGroup`**, 

to describe the group containing all persons that have the rights of members of the Community, i.e.:

- those who registered as Ordinary Members of the Community;
- those who registered as Cooperators, but have not fulfilled their obligations to be full Cooperators, because: (a)  they have not acquired their share; (b) they have not paid their initial yearly contribution; (c) their previous yearly contribution has expired, etc. as described in full detail in issue #148 ;
- those who egistered as Cooperators, but were sanctioned (same reference).

**Comment by michaellaunay** [comment]
Done
