### ISSUE TITLE
Some elements in the login page are not displayed securely: message "insecure connection"

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#21]
When logging in, the page is not completely secured. Some elements in the login page (the images?) are not secure. 
Therefore, the Firefox browser warns of a possible security leak when submitting the ID + password: 
"Les informations saisies vont être transmises en clair (sans chiffrement). Elles peuvent donc éventuellement être interceptées et lues lors de leur acheminement.
Voulez-vous vraiment transmettre ces informations ?"
I don't know if this is true. Even if not, precautions must be taken to avoid having this disquieting message being displayed, and to make the transmission of ID + password fully secured with full https protocol.

**Comment by michaellaunay** [comment]
Rejected, as it pertains to the nginx configuration of publicpolicies.cosmopolitifcal.coop, even though it needs to be done.
