### ISSUE TITLE
The confirmation message contains code instead of clear text

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#23]
The e-mail body containing the confirmation of the registration contains source code instead of clear text.
The e-mail body was again received on Thunderbird as a separate, non-immediately readable, html attachement, called "Partie 1.2".

The issues are:

- the name of the type of candidature is provided as "CandidatureTypes.ORDINARY" 
- the name of the new statute is provided as: "CandidatureStates.CONFIRMED_HUMAN"
On each occasion, this code should have been replaced by the proper associated text in the target language.

The e-mail body is the following:

<!DOCTYPE html>
<html>
<head>
    <title>Changement de Statut de Votre Candidature</title>
</head>
<body>
    <h1>Évolution de Votre Candidature</h1>
    
    <p>Bonjour laurent_zibell,</p  >
    
    <p>Votre candidature sur la plateforme http://alirpunkto.cosmopolitical.coop/ en tant que CandidatureTypes.ORDINARY
        
        
        <span>est en cours de traitement et a changé de statut</span>
        .
    </p>
    
    <p>Voici les détails de son évolution :</p>
    <ul>
        <li>ID de la Candidature : 79ee101f-0dd7-483b-abdf-cb0bc455b68e</li>
        <li>Date de Transition : 2023-10-06 06:58:17.301984</li>
        <li>Nouveau Statut : CandidatureStates.CONFIRMED_HUMAN</li>
        <li>
            <a href="[http://alirpunkto.cosmopolitical.coop/register?oid=gAAAAABlH7AJYsKgvC_s8b6D5xHl_h-VxkOKjNYACZROJetpJNwaWfeAxPYU0DJV7Tu5UO196aDxtiLq8dnacPQgNuHLkp1cNuBKq7rkhE28yvcTS_7xuJulxbpQTl0ITjhJ1bc-4msc](view-source:http://alirpunkto.cosmopolitical.coop/register?oid=gAAAAABlH7AJYsKgvC_s8b6D5xHl_h-VxkOKjNYACZROJetpJNwaWfeAxPYU0DJV7Tu5UO196aDxtiLq8dnacPQgNuHLkp1cNuBKq7rkhE28yvcTS_7xuJulxbpQTl0ITjhJ1bc-4msc)">
            http://alirpunkto.cosmopolitical.coop/register?oid=gAAAAABlH7AJYsKgvC_s8b6D5xHl_h-VxkOKjNYACZROJetpJNwaWfeAxPYU0DJV7Tu5UO196aDxtiLq8dnacPQgNuHLkp1cNuBKq7rkhE28yvcTS_7xuJulxbpQTl0ITjhJ1bc-4msc
            </a>
        </li>
    </ul>
    
    <p>Merci pour votre participation.</p>
    
    <p>Cordialement,</p>
    <p>L'équipe de Alirpunkto</p>
</body>
</html>

**Comment by michaellaunay** [comment]
Done in 860d700e5dd19ec44229fa89ba5db90342d0389a commit.
