### ISSUE TITLE
Verification e-mail in plain text format contains HTML tags

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#31]
The e-mail to verify that the user is a human (= with the 4 mathematical challenges), in plain text format, contains some residual HTML `<div>` tags.

Here is the text e-mail I received.

```

     <div omit-tag="textual"> 
        Operation A is 1 times 4 plus 3
        Operation B is 1 times 3 plus 6
        Operation C is 7 times 2 plus 7
        Operation D is 3 times 2 plus 7
    </div>

```

This applies as well to the e-mail reporting on the changes in the status of the application:
```
 Your application on the platform http://alirpunkto.cosmopolitical.coop/ as a CandidatureTypes.ORDINARY
        
        
        <span>is under processing and has changed its status</span>
        .
    
    
    Here are the details of its evolution:
```

**Comment by michaellaunay** [comment]
"Resolved the issue as per commit eea787ba52a587d34b2daeddd0ef7c77952944e7, which includes fixes and enhancements addressing the reported problem."
