### ISSUE TITLE
When registered as an Ordinary Member of the Cooperative, the login does not work

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#32]
I have registered as an Ordinary Member of the Cooperative and completed the process.
When I attempt to login with the credentials I had on the [login page](https://alirpunkto.cosmopolitical.coop/login), nothing happens: 

- I remain on the same page
- I receive no information whether my credentials (ID + password) were correct or not. 

When I go to the ["Forgot password" page](https://alirpunkto.cosmopolitical.coop/forgot_password), I see that there is no reaction when I provide the e-mail address that I had used upon registration: 

- no acknowledgement of receipt of the request by the system, 
- no error message.

This would indicate that the registration in the LDAP directory has not worked.

**Comment by michaellaunay** [comment]
Done
