### ISSUE TITLE
Addressing Fixed Form Issue in Literal Mathematical Expressions

### ISSUE THREAD

**Issue by michaellaunay** [michaellaunay/alirpunkto#59]
# Description:

## Problem:
There is an issue with the fixed form in the translation and literal representation of mathematical expressions in French. Specifically, the literal expression "Un fois trois plus quatre" should correctly be "Une fois trois plus quatre". This issue arises when converting numbers into words in mathematical operations.

## Impact:
This inaccuracy affects the clarity and precision of mathematical expression when rendered in French. It can lead to confusion, especially in educational contexts or user interfaces where linguistic accuracy is crucial.

## Proposed Solution:
A rule or mechanism needs to be implemented that respects the fixed forms of the French language, particularly for the expression "une fois," which is used regardless of the gender of the following number.

## Suggested Steps:

    Identify all occurrences where mathematical expressions are converted into text.
    Implement conditional logic or a specific rule to correctly handle the fixed form "une fois" in French.
    Ensure this logic is consistently applied across the application.
    Conduct extensive testing to verify that the correction is correctly applied in different situations.

## Expected Outcome:
After implementing this correction, mathematical expressions should be rendered correctly, respecting the linguistic peculiarities of French, thereby improving the precision and professionalism of communication in the application.

## Additional Question:
Do other languages have an equivalent to the French fixed form in their mathematical expressions? For example, is there a similar linguistic phenomenon where the literal translation of mathematical operations deviates from direct numeral translations due to traditional or grammatical reasons?

**Comment by SergioArbarviro** [comment]
I propose as a simple linguistic fix the following: use "_multiplié par_" instead of "_fois_", i.e. "multiplied by" instead of "times".
The translation into other languages should be unambiguous, as these expressions refer explicitly to the context of mathematical operations.

**Comment by michaellaunay** [comment]
Implemented by 7349e910c1a8f0df38c599647b7789e6bfc659a2 commit
