### ISSUE TITLE
Title on the welcome page and on the login page does not match the .POT file

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#68]
The titles on the [welcome page](https://alirpunkto.cosmopolitical.coop/) and on the [login page](https://alirpunkto.cosmopolitical.coop/login) are identical and do not match those of the [alirpunkto/locale/alirpunkto.pot](alirpunkto/locale/alirpunkto.pot) file.

**Comment by michaellaunay** [comment]
The message key in the PO file is:
msgid "welcome_msg"
msgstr "Welcome to Alirpunkto, the centralized service for applications used in the IT infrastructure of ${site_name}."

However, I have regenerated the .mo file and updated the deployment.

**Comment by SergioArbarviro** [comment]
After resolution of the Issue #66 the only remaining issue is that the variable ${site_name} has the value "AlirPunkto" while it should have that of "CosmoPolitical Cooperative SCE"

**Comment by SergioArbarviro** [comment]
The title of the login page `/login` still contains **AlirPunkto** and **alirpunkto.org** instead of the values for `${site_name}` and for `${domain_name}`, respectively.

**Comment by michaellaunay** [comment]
Done
