### ISSUE TITLE
The registration process must implement the hierarchical structure of groups

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#73]
The current groups existing in the LDIF descriptor are:

- ordinaryMembersGroup
- cooperatorsGroup
- boardMembersGroup
- mediationArbitrationCouncilGroup

These groups are structured hierarchically: ordinaryMembersGroup **includes** cooperatorsGroup **includes** (boardMembersGroup **union** mediationArbitrationCouncilGroup)

The registration process must implement this hierarchy:

- when a person registers as an Ordinary Member of the Community, s/he is included in  the **ordinaryMembersGroup**;
- when a person registers as a Cooperator, s/he must be included in **both** the **cooperatorsGroup** and the **ordinaryMembersGroup**;
- only members of the **cooperatorsGroup** are allowed to be promoted to members of the **boardMembersGroup** or of the **mediationArbitrationCouncilGroup**.

**Comment by michaellaunay** [comment]
See #74
