### ISSUE TITLE
Add variables linked to management of 'groups': uniqueMember - uniqueMemberOf

### ISSUE THREAD

**Issue by SergioArbarviro** [michaellaunay/alirpunkto#90]
In order to manage the groups and their members, the KeyCloak OAuth server requires that the following variables be managed.

For each **group**, the list of its members, with the following syntax:

**uniqueMember**: uid=[UID of the member], dc=[domain name], dc=[TLD of the domain name]

(e.g. uniqueMember: uid=400383ed-dc1a-41d6-ae87-7db25344a2b8,dc=cosmopolitical,dc=coop)
This field is repeated as many times as there are members in the group.

For each **user**, the list of the groups that s/he belongs to, with the following syntax:

**uniqueMemberOf**: cn=[name of the group],dc=[domain name], dc=[TLD of the domain name]
(e.g. uniqueMemberOf: cn=ordinaryMembersGroup,dc=cosmopolitical,dc=coop)
This field is repeated as many times as there are groups to which the user belongs.

I propose that these variables be implemented and managed by AlirPunkto.

**Comment by ldidry** [comment]
> For each group, the list of its members, with the following syntax:
> uniqueMember: uid=[UID of the member], dc=[domain name], dc=[TLD of the domain name]

NB: This is already handled in AlirPunkto.
